<?php

include('duo_web.php');

/*
 * This is something uniquely generated by you for your application
 * and is not shared with Duo.
 */
define('AKEY',"Make up a long random string it can be anything you like!!QQ%%&$");

/*
 * IKEY, SKEY, and HOST should come from the Duo Security admin dashboard
 * on the integrations page.
 */
define('IKEY',"XXXXXXXXXXXXXXXXXXXX");
define('SKEY',"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
define('HOST',"XXXXXXXXXXXX.duosecurity.com");

?>
